### ISSUE TITLE
mnt/teamspeak is empty?

### ISSUE THREAD

**Issue by Petoj87** [overshard/docker-teamspeak#11]
Im no Linux guy by any means but after starting the docker image.
i wrote `cd ..` until i was in the root folder `docker@boot2docker:/$` then i used `cd mnt/teamspeak`
now if i write `ls` there the directory is empty..
So where do i find the log file with the admin key?

i used the following to start `sudo docker run -d=true -p=9987:9987/udp -p=10011:10011 -p=30033:30033 -v=/mnt/teamspeak:/data overshard/teamspeak /start`

Also i got a few errors while building:
```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
```
do i need to care about those?

`sudo docker ps` results in
```
CONTAINER ID        IMAGE                 COMMAND             CREATED             STATUS              PORTS                                                                        NAMES
0d8ba6b1c6a3        overshard/teamspeak   "/start"            14 minutes ago      Up 14 minutes       0.0.0.0:10011->10011/tcp, 0.0.0.0:9987->9987/udp, 0.0.0.0:30033->30033/tcp   sharp_lalande
```

**Comment by Petoj87** [comment]
Tried a clean install but still same problem there is no logfile to be found, i even tried to use `docker exec -t -i dd14e2add459 /bin/bash` to look for it but no success..

**Comment by pjgranahan** [comment]
I'm running into this problem as well. `/mnt/teamspeak` has no files after running `sudo docker run -d=true -p=9987:9987/udp -p=10011:10011 -p=30033:30033 -v=/mnt/teamspeak:/data overshard/teamspeak /start`, but I am able to connect to the server.

**Comment by Petoj87** [comment]
I gave up on this release and picked one from dockerhub instead and it worked as intended.

**Comment by overshard** [comment]
Should be fixed in the latest release, I pulled an update a while ago that involved implementing user isolation. While is is a great idea and should always be done for security it is breaking how we store files. I've removed it for now till I can take a closer look at it.
