### ISSUE TITLE
connected client IP is the local container IP

### ISSUE THREAD

**Issue by malbin** [overshard/docker-teamspeak#13]
This seems like unexpected behavior. From my logs:

`2016-02-04 05:55:14.916204|INFO    |VirtualServerBase|  1| client connected 'malbin'(id:2) from 172.17.0.1:41840`

Emphasis on 172.17.0.1 which is definitely not the remote client's IP. Wondering if I'm missing something silly here.

**Comment by defaye** [comment]
This might be an issue with running docker containers in general CMIIAW

**Comment by overshard** [comment]
I don't think there is anything we can fix here really, it's just this will work with TeamSpeak, it needs to be corrected at a software level to identify proxying on the TeamSpeak server itself.
