### ISSUE TITLE
Docker hub?

### ISSUE THREAD

**Issue by ccatlett2000** [overshard/docker-teamspeak#22]
Would it be possible for you guys to set up a simple autobuild on docker hub for this to make it easier for people to use?

**Comment by bufanda** [comment]
I have prepared an build based on my fork. You are welcome to use it ;) 
Just do
docker pull bufanda/teamspeak

**Comment by shoeper** [comment]
That would likely not be covered by the teamspeak license.

**Comment by overshard** [comment]
This is technically not allowed by teamspeak so I don't plan on doing this
