### ISSUE TITLE
Run teamspeak as unprivileged user

### ISSUE THREAD

**Issue by jaltek** [overshard/docker-teamspeak#6]
Hi,

just for the paranoid ones of us:
Although this app is running inside a container, Teamspeak should run as unprivileged user. 

https://forums.docker.com/t/root-user-or-non-root-user-inside-container/966/3
https://groups.google.com/forum/#!msg/docker-user/e9RkC4y-21E/JOZF8H-PfYsJ

What do you think?

**Comment by Nextgensource** [comment]
a little late, but I just did this this myself(its really easy). Pull [this](https://github.com/Nextgensource/docker-teamspeak) if you still need it.

**Comment by overshard** [comment]
I agree this should be done, if anyone wants to do a pull request for it I'll merge.

**Comment by XanderXAJ** [comment]
It looks like this was merged with 78f2f2dcb35489b2ebbbf0e239ba3d55d9ad083c, so this can be closed now?

**Comment by overshard** [comment]
I've reverting it due to the update not functioning properly, so this is still an issue.

**Comment by overshard** [comment]
The issue is the files we store in /data and on the primary machine /mnt/teamspeak aren't properly owned by the teamspeak user. This causes the system to break at the moment.

**Comment by overshard** [comment]
This is fixed in the latest pull request, it's working great now!
